version: "2"

services:
    php:
        image: php:7-alpine
        container_name: test_php
        volumes_from:
            - data
    nginx:
        build:
            context: .
            dockerfile: nginx-dockerfile
        links:
            - php
        ports:
            - "10443:443"
            - "10080:80"
        container_name: test_nginx
        volumes_from:
            - data
    data:
        container_name: test_data
        build:
            context: .
            dockerfile: data-dockerfile
